### PR TITLE
Merge Develop to Master

### PR DESCRIPTION
**Pull request by davelab6**
Master hasn't been updated in 2 years, but Develop is actively maintained. 

I suggest merging Develop to Master and working on Master.

### CODE REVIEW

**Comment by davelab6** [comment]
@lianghai ping

**Comment by lianghai** [comment]
Basically I can't afford maintaining API stability for outside users (if any)… I'll merge `GoogleFonts` (the branch I use to compile Google Fonts projects) to `master` instead, while leaving `develop` unstable.

**Comment by lianghai** [comment]
Done.

**Comment by davelab6** [comment]
Cool, thanks for clarifying :)

**Comment by davelab6** [comment]
However, I don't see that branch in https://github.com/itfoundry/hindkit/branches

**Pull request closed without merging**
